# Site settings
title: "One Photon"
author: "prakash"   # or your preferred name
description: "..and infinite darkness."

# Contact & Social media (optional — remove if not needed)
email: "yourmail@example.com"
twitter_username: "yourtwitter"
github_username: "onephoton"   # or your actual GitHub username
linkedin_username: "yourlinkedin"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

# Build settings
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Thoughts
